### ISSUE TITLE
notices link is broken

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/oncommand-insight#13]
### Page URL

https://docs.netapp.com/us-en/oncommand-insight/install-linux/installation-prerequisites.html

### Page title

Installation prerequisites

### Summary

if you need to reference the notices from here, you might want to just link to the notices heading in your common legal page. visitors can click through as needed, and there's less risk of a bad link.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
I have updated the link on both the Linux and Windows pages to point to the Notices doc page instead.
