### ISSUE TITLE
Request to add supported auth method

### ISSUE THREAD

**Issue by norah-netapp** [NetAppDocs/oncommand-insight#15]
### Page URL

https://docs.netapp.com/us-en/oncommand-insight/config-admin/configuring-sso.html

### Page title

Configuring Single Sign-On (SSO)

### Summary

I have a case where the customer is trying to configure SSO using Okta. The OCI dev team provided feedback that this feature was only tested/supported only using Azure AD. The document needs to have that this feature only supports Azure AD engineering has mentioned there are no plans on taking new features for OCI.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Thanks for this feedback.  I have confirmed that SSO is only supported with Azure AD and will add that as a note in the documentation.

**Comment by netapp-alavoie** [comment]
SSO support has been removed from OCI, so this page is no longer available.
