### ISSUE TITLE
Update command example for step 2 so the different OS commands are on separate lines

### ISSUE THREAD

**Issue by dawnr-netapp** [NetAppDocs/oncommand-insight#17]
### Page URL

https://docs.netapp.com/us-en/oncommand-insight/config-admin/managing-security-on-the-data-warehouse.html

### Page title

Managing security on the Data Warehouse

### Summary

This line in step 2 needs to be broken into two lines, since it's intended to be how to run it on different OS.

Windows - C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i``Linux - /bin/oci-securityadmin.sh -i

It should be:
2. Start the security admin tool in interactive mode: 
    Windows - C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i
    Linux - /bin/oci-securityadmin.sh -i
    The system requests login credentials.

It's also incorrect in the same way on this page:
https://docs.netapp.com/us-en/oncommand-insight/config-admin/managing-security-on-an-rau.html#steps

And to add to the confusion, these other two pages word it differently. All of them should match. Doesn't matter which one as long as it's consistent, but i prefer the first example after it's been corrected be used instead of one of the two below.

https://docs.netapp.com/us-en/oncommand-insight/config-admin/managing-security-on-the-insight-server.html#steps
2. Start the security admin tool in interactive mode: securityadmin -i
    The system requests login credentials.

https://docs.netapp.com/us-en/oncommand-insight/config-admin/managing-security-on-the-local-acquisition-unit.html#steps
2. Start the security admin tool in interactive mode (-i).
    The system requests login credentials.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
Thanks for this feedback, Dawn!  Looks like a formatting glitch (and a possible benefit from a quick copy and paste action) for the first items at least.   I'll take a look and get these corrected.

**Comment by netapp-alavoie** [comment]
These should be all formatted better now.  Please open a new ticket if you notice any other places we want to fix.
