### ISSUE TITLE
Request vendor-specific reference for HDS Ops Center data source

### ISSUE THREAD

**Issue by brhoffa** [NetAppDocs/oncommand-insight#8]
### Page URL

https://docs.netapp.com/us-en/oncommand-insight/config-admin/vendor-specific-data-source-reference.html

### Page title

Vendor-specific data source reference

### Summary

Service Pack 10 for OnCommand Insight 7.3.x introduced a data source for HDS Ops Center (see https://mysupport.netapp.com/site/products/all/details/oncommand-insight/downloads-tab/download/60983/7.3SP10/downloads). Should the docs now have instructions on how to use the data source?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
The HDS Ops Center collector has been added: https://docs.netapp.com/us-en/oncommand-insight/collector_hds_ops_center.html. Please open a new ticket if any information appears incorrect.

Thanks for helping improve OCI Documentation!
-Tony
